### ISSUE TITLE
Please add tally and record controls to JVC-PTZ Module!

### ISSUE THREAD

**Issue by ryanjohnclark** [bitfocus/companion-module-jvc-ptz#2]
Hi guys! Bounty offered to add to JVC-PTZ:
Instance feedback for:
Tally lamp status pg 32 section 3.3.1
Record Status pg 31 section 3.3.1
Actions for:
Recording functions pg 38 section 3.3.2
Tally lamp control pg 41 section 3.3.5
Please let me know if someone can add them and cost.  Thanks!

[JvcCamcorderApiReferenceV107_public.pdf](https://github.com/bitfocus/companion-module-jvc-ptz/files/4467559/JvcCamcorderApiReferenceV107_public.pdf)

**Comment by JeffreyDavidsz** [comment]
Hey Ryan, I've added the actions

**Comment by JeffreyDavidsz** [comment]
For the feedback function, we would need to connect a camera again. Will take a hour/45min to build in the feedback function, with those options.

**Comment by ryanjohnclark** [comment]
Can you remind me of what an appropriate bounty would be for the work? I
went back through our earlier correspondence but must have deleted it.

**Comment by validlogin** [comment]
Wow, what great timing! We just needed this function!

I can confirm that the Tally controls, as well as the zoom in/zoom out, gain control, etc. all work for the JVC GY-HM200 cameras we have. Focus control doesn’t seem to be working but push auto focus does work. The zoom function presets also only work if you click several times, but there is another zoom function that you can select manually that’ll let you use the zoom more smoothly.

Is there a way to have the tally lights only have one camera at a time be set to PGM? 

We have stream deck setup to a switcher, so that when you select a camera on preview, a function comes directly after it that tells that specific camera to enable the PVW tally light, as well as a function to disable all other camera’s tally lights.

However, when we decide to select a camera to go live, there’s really no way for us to make that one camera switch from PVW to PGM. 

Is there some way to add a function similar to this: If the tally light is on Preview, then switch to Program. This would be greatly helpful. We’ve been Messing around in companion but haven’t been able to find a method to do this.

My apologies if this is in the incorrect section, this is our first time using Github, and the companion software, but we absolutely love it:)

**Comment by JeffreyDavidsz** [comment]
Hi @validlogin some functions don't work on specific camera's. You should be able to use preview and program tallys. But again this could be a camera thing. I have checked the feedback against a PZ100 and the status was preview and program when I switched between. So to be clear, you should just change the dropdown of the action to program and press test action to test it.

**Comment by validlogin** [comment]
@JeffreyDavidsz - thanks for the quick response!

I’m not saying there’s any issues with this module, in fact, everything works as we need it:) including tally lights. We don’t have any issues with that.

My question, and this might be more of a Companion limitation, is if there is a way to have an action be completed ONLY if some variable is met.

In other words, I understand that it’s possible to check (via feedback) what state a tally light is in. However, is there a way to have an action be dependent on the state of the tally? To simplify this, imagine a function set up like this: 
If the tally light is on PGM, then ...
or
If the tally lights is on PVM, then..

It seems like this might be more of a limitations of Companion at this point. If this is the incorrect section for this please let me know where I can find more help, I’m pretty new here :)

**Comment by JeffreyDavidsz** [comment]
Is possible within the module itself. So the question is what do you want to accomplish?
I would assume you want the light on program when it's on program. So the same button you use to switch that camera to program, you use that to set the tally to pgm, right?

**Comment by ryanjohnclark** [comment]
I assume its the same issue I have where the switcher knows what is in pgm
and what is in pvw but can't relay that to the cameras. I have a work
around for my situation but in order for it to work best it would need
feedback from the switcher.  I wouldn't know how to make this work for all
switchers but, like many things in Companion,  I wish I was smart enough to
get in there and code what I know I want!

**Comment by validlogin** [comment]
We just want to have the cameras which are on preview (on the switcher) also have the tally set to PVW, and then have the camera which is on program to have the tally set to PGM. We have the first part of this working, but I’m just not sure how to get the PGM part to work.

Our stream deck is set up like this: we have a button for each camera input on the switcher, and when you click on a camera, it’ll set that camera as the preview (in addition, the button also sets the tally light to PVW). When you switch to a different camera to preview, the button disables all the tally lights for the other cameras, and enables the PVW tally light for the camera you selected.

If you want that camera to go “live”, or on program, you just hit a “cut” button, which then throws the camera selected as preview as live.

With this setup, there really isn’t a way to have program lights working, since there’s only one button that controls what’s on the program. We could get it to work by having a second set of buttons for each camera to make them go live, but this is 8 extra buttons compared to one.

The only way I see this working with one button is by having some sort of “check” that can see if the camera’s tally light is set to preview, and then switching it to program. There isn’t a need to have it communicate with the switcher, although that might also work.

I hope that makes sense, it is pretty complicated without being able to physically show you the setup:)

**Comment by JeffreyDavidsz** [comment]
It's clear now, I can make an action which checks the tally status and when on preview, switch to program. Only downside is I cannot control (at the moment) when 2 cameras are in preview. They would both switch to PGM. So this should be in the back of mind when for example using 2 ME's

**Comment by JeffreyDavidsz** [comment]
I've build it in, please check because I couldn't test now. For each camera you put an action on the cut button. That way it will check each camera for status and change it when needed to PGM

**Comment by validlogin** [comment]
Can it be done? We're in no hurry to get this implemented so:) I'm really not sure how Github works with bounty and what not!

That's perfect for our use case. Not sure about others however, as I do know some people who use several switchers. At that point there would need to be some way to pull the information from the switcher, and then somehow tie the inputs to each camera.

**Comment by validlogin** [comment]
Oh wow! I just saw that was already added! Guess I'll try it out tomorrow and report back:)

**Comment by JeffreyDavidsz** [comment]
Please report back yes. This is a special additional for your use case, but could help others also. This way you don't need to go cross module. I would assume we will build something like that but my guess is that it will come in 3.0.

**Comment by smayberry** [comment]
I haven't looked at this module yet, but you might be interested to see what was done in the panasonic-ptz module. It watches a dynamic variable (of the switcher module) to determine whether the camera's tally should be on.

**Comment by validlogin** [comment]
I wasn't able to test out the feature today, unfortunately, but I did a few "simulations" in my head and realized that there would need to be additional "checks" added to make this work, which I didn't realize at first... an oversight on my part, my bad!

1) If a camera is "live" and the tally is set to Program, previewing that camera again (the ATEM allows the same input to be both on preview and program) will over-ride the Program status and put it in a Preview state. A fix would be to add a Tally Off -> Tally check PGM, so that no changes will be made to the tally state if the tally is set to PGM, like this:
`case 'checkOFFtoPVW':
					if (this.tally == "Off") {
						jvcPTZObj.Request = { "Command": "SetStudioTally", "SessionID": this.sessionID, "Params": { "Indication": 'Preview' } }
					}`

2) Adding onto this issue, a PVW -> Off check would need to be added because each input manually turns off the tally for every other camera, to ensure that there is no more than one camera on Preview.. but this would also affect the camera that is live. Something like this: 
`case 'checkPVWtoOFF':
					if (this.tally == "Preview") {
						jvcPTZObj.Request = { "Command": "SetStudioTally", "SessionID": this.sessionID, "Params": { "Indication": 'Off' } }
					}`

3) Lastly, there's no way to disable the tally from PGM to off or PVW (unless I missed this in the code) when selecting another camera to go live. A PGM -> Off check would also need to be added.

(Note, the snippets of code were just quick changes @JeffreyDavidsz work as examples, I have no idea if the syntax or variables are correct)

@smayberry That's quite an interesting feature, and it would solve having more than one switcher at a time. Maybe this could be implemented rather than the quick and dirty suggestions I had? ;p
